name: Deploy Lambda to AWS

on:
  push:
    branches: [main]  # Or your working branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Zip Lambda function
        run: zip -j function.zip backend/stockFetcher.js

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name stockLambda \
            --zip-file fileb://function.zip